python main.py m5-forecasting.Predict --from-date 1914 --to-date 1915 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1915 --to-date 1916 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1916 --to-date 1917 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1917 --to-date 1918 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1918 --to-date 1919 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1919 --to-date 1920 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1920 --to-date 1921 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1921 --to-date 1922 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1922 --to-date 1923 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1923 --to-date 1924 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1924 --to-date 1925 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1925 --to-date 1926 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1926 --to-date 1927 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1927 --to-date 1928 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1928 --to-date 1929 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1929 --to-date 1930 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1930 --to-date 1931 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1931 --to-date 1932 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1932 --to-date 1933 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1933 --to-date 1934 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1934 --to-date 1935 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1935 --to-date 1936 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1936 --to-date 1937 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1937 --to-date 1938 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1938 --to-date 1939 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1939 --to-date 1940 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1940 --to-date 1941 --interval 1 --local-scheduler
python main.py m5-forecasting.Predict --from-date 1941 --to-date 1942 --interval 1 --local-scheduler